version: "3.9"

services:
  app:
    container_name: pki-2fa-service
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "8080:8080"

    volumes:
      # App runtime directories
      - seed-data:/data
      - cron-output:/cron

      # PEM key mounts (read-only)
      - ./student_private.pem:/app/student_private.pem:ro
      - ./student_public.pem:/app/student_public.pem:ro
      - ./instructor_public.pem:/app/instructor_public.pem:ro

      # Mount cron scripts
      - ./docker/run_2fa_cron.sh:/app/run_2fa_cron.sh:ro
      - ./docker/cron/2fa-cron:/etc/cron.d/2fa-cron:ro

    environment:
      TZ: UTC

    restart: unless-stopped

volumes:
  seed-data:
  cron-output:
